### ISSUE TITLE
No motor 

### ISSUE THREAD

**Issue by vinodmadhu6** [benbusby/raztot#2]
You are not using a H bridge.. a motor driver. Won't you burn the raspberry pi ? 
How did you solve this ?

**Comment by benbusby** [comment]
You don’t need an H bridge. Sending the right pwm values to the servos accomplishes clockwise/counterclockwise rotation (1500µs as center, >1500 = clockwise, <1500 = counterclockwise). 

The 5V pins on the raspberry pi are fine for powering the two small servos and nothing will get damaged on the board.
